        stage('Build Docker Image') {
            steps {
                sh '''
                cd app
                docker build -t devops-capstone-app:latest .
                '''
            }
        }

        stage('Stop Existing Container') {
            steps {
                sh '''
                docker ps -q --filter "publish=5000" | xargs -r docker stop
                docker ps -aq --filter "publish=5000" | xargs -r docker rm
                '''
            }
        }

        stage('Run New Container') {
            steps {
                sh '''
                docker run -d --name devops-capstone -p 5000:5000 devops-capstone-app:latest
                '''
            }
        }

