pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/babil123:/devops-capstone-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                cd app
                docker build -t devops-capstone-app:latest .
                '''
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                docker rm -f devops-capstone || true
                '''
            }
        }

        stage('Run New Container') {
            steps {
                sh '''
                docker run -d --name devops-capstone -p 5000:5000 devops-capstone-app:latest
                '''
            }
        }
    }
}

